apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: original-pvc
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    request.autodiskscaling.kubecost.com/enabled: "true"
    request.autodiskscaling.kubecost.com/interval: 7h
  name: busybox-deployment
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: busybox
        name: busybox
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /app/folder
          name: volume
      initContainers:
      - command:
        - sh
        - -c
        - date > /app/folder/date.txt
        image: busybox
        imagePullPolicy: Always
        name: echo-date
        resources: {}
        volumeMounts:
        - mountPath: /app/folder
          name: volume
      securityContext: {}
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: original-pvc
