apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-role-binding
subjects:
- kind: ServiceAccount
  name: demo-service-account
  namespace: kubecost
roleRef:
  kind: Role
  name: demo-role
  apiGroup: rbac.authorization.k8s.io